### ISSUE TITLE
Xamarin Forms

### ISSUE THREAD

**Issue by LumiProj** [ALE-Rainbow/Sharp.Ws.Xmpp#1]
Hi,

Can we use this in Xamarin Forms.

Thanks

**Comment by ChristopheI** [comment]
Hi,
Yes you can use it in Xamarin Forms.
You can take a look to this project using it and working on Android and iOS
https://github.com/Rainbow-CPaaS/Rainbow-CSharp-SDK-Samples/tree/master/MobileApplication/InstantMessaging

There is some screenshots here:
https://github.com/Rainbow-CPaaS/Rainbow-CSharp-SDK-Samples
